### ISSUE TITLE
No Smily face on the gateway

### ISSUE THREAD

**Issue by Copterrichie** [nlmaca/Enecsys_RPI_images#1]
Hello, I like the idea using a Raspberry PI to monitor my enecsys system. I believe I have followed the install instructions to the letter trying both the manual and disk image however, I am unable to get a Smiley Face on the gateway nor data in the dashboard. I entered all of the Inverter information including serial numbers and pointed the remote server address to the Raspberry Pi. I know the data is being received and sent via the gateway to EnecysyOutput site. Any suggestions?

Thank you.

**Comment by nlmaca** [comment]
Hi Copterrichie,
I cant tell you what to do about the smiley faces. You might have to ask your mechanic for that. it could be a broken inverter, or inverter out of reach.
i kinda wonder if you dont have a smiley face on your gateway that you still can have data in pvoutput, because you might miss out on some inverters.

if you want to show the data in the dashboard, did you create a database for it and did you enter them in the installer script? 
the e2pv script can run without the dashboard. the dashboard relies on the input into the database, i think that is where the dashboard part is stuck. 

Can you tell me which steps you did so i can point out where it might wrong?
If you can give me some more detail information or send me some screenshots of your config file and the dashboard i might can help you with that. just send them to jeroen@vanmarion.nl so you dont have to post this in public.

**Comment by Copterrichie** [comment]
I found the problem, syntax errors in the config.php file. Apparently, 
pressing enter to select the default generates a null entree some of the 
define statements for example define('LIFETIME',0 );


Thank you.

**Comment by nlmaca** [comment]
nice. good you could find the solution. thx for the feedback. im aware of the default questions. i thought it would be ok, but more people used the enter button instead (which was not how i build it). in my new version i took care of that. hope to launch it somewhere in november.

**Comment by Copterrichie** [comment]
Thank you, I am available to alpha/beta test if needed.


Richard
